### PR TITLE
Changes to Header.js/Home.js/App.css

### PR DESCRIPTION
**Pull request by ChiaKuo**
- Added Header and Paragraph Text (Home.js)

- fade-in animations for text (App.css)

- slide-in logo from the top in header (Header.js)

- button styling (App.css)

### CODE REVIEW

**Comment by epwallace** [comment]
Hey Chia, looks good so far. It's nice to finally see the site name on the main page. One thing I noticed is lorem welcome text is in the same place as the button, so we should probably space those out before we merge. As far as the effects go, the slide down header feels a bit like an advertisement to me. I'd personally prefer a stationary header in the upper left, but that's just my opinion (not sure what @NehaSuthar and @darienweise think). I also don't think the start button needs a fade-in, but I'm happy to keep it if everyone likes it.

**Comment by epwallace** [comment]
Oh, I just noticed everything fades in, not just the button. I take it back, it looks nice!

**Comment by darienweise** [comment]
The fade in is very impressive, i like this change. I am down to commit this.
Screen Shot 2020-10-04 at 1 53 10 PM

**Comment by epwallace** [comment]
I agree, it's looking great. Let's merge it in! 👍

**Pull request merged**
